
import express from 'express';
import authRoutes from './authRoutes';
import serviceRoutes from './serviceRoutes';
import employeeRoutes from './employeeRoutes';
import bookingRoutes from './bookingRoutes';
import customerRoutes from './customerRoutes';
import productRoutes from './productRoutes';
import roomRoutes from './roomRoutes';
import membershipRoutes from './membershipRoutes';
import loyaltyRoutes from './loyaltyRoutes';
import paymentRoutes from './paymentRoutes';
import attendanceRoutes from './attendanceRoutes';
import marketingRoutes from './marketingRoutes';
import analyticsRoutes from './analyticsRoutes';
import settingsRoutes from './settingsRoutes';
import contactRoutes from './contactRoutes';
import packageRoutes from './packageRoutes';
import uploadRoutes from './uploadRoutes';
import galleryRoutes from './galleryRoutes';
import reportRoutes from './reportRoutes';
import leaveRoutes from './leaveRoutes';
import notificationRoutes from './notificationRoutes';
import taxRoutes from './taxRoutes';
import crmRoutes from './crmRoutes';
import geofenceRoutes from './geofenceRoutes';
import careerRoutes from './careerRoutes';
import helpRoutes from './helpRoutes';

const router = express.Router();

router.use('/auth', authRoutes);
router.use('/services', serviceRoutes);
router.use('/employees', employeeRoutes);
router.use('/bookings', bookingRoutes);
router.use('/customers', customerRoutes);
router.use('/products', productRoutes);
router.use('/rooms', roomRoutes);
router.use('/memberships', membershipRoutes);
router.use('/loyalty', loyaltyRoutes);
router.use('/payments', paymentRoutes);
router.use('/attendance', attendanceRoutes);
router.use('/marketing', marketingRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/settings', settingsRoutes);
router.use('/contacts', contactRoutes);
router.use('/packages', packageRoutes);
router.use('/upload', uploadRoutes);
router.use('/gallery', galleryRoutes);
router.use('/reports', reportRoutes);
router.use('/leaves', leaveRoutes);
router.use('/notifications', notificationRoutes);
router.use('/taxes', taxRoutes);
router.use('/crm', crmRoutes);
router.use('/geofence', geofenceRoutes);
router.use('/careers', careerRoutes);
router.use('/help', helpRoutes);

export default router;
